#!  /usr/bin/env python3

import argparse
import base64
import gzip
import json
import os
import sys

def main(argv):
    #   Don't buffer standard output.
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', -1)

    parser = argparse.ArgumentParser()

    parser.add_argument \
        ('--verbose', dest='verbose', action='count', default=0,
         help='verbosity level')

    #   Parse command-line arguments.
    arg = parser.parse_args()

    json_data = sys.stdin.buffer.read()

    if arg.verbose:
        print('json_data', json_data, file=sys.stderr)

    compressed = gzip.compress(json_data)

    if arg.verbose:
        print('compressed', compressed, file=sys.stderr)

    encoded = base64.b64encode(compressed)

    if arg.verbose:
        print('encoded', encoded, file=sys.stderr)

    obj = \
        {
        'context'   : { },
        'event'     : \
            {
            'awslogs'   : \
                {
                'data'  : encoded.decode(),
                },
            },

        }

    print(json.dumps(obj, indent=4))

    return 0

#####

if __name__ == '__main__':
    sys.exit(main(sys.argv))
