#!  /usr/bin/env python3

import argparse
import base64
import gzip
import json
import os
import sys

from attrdict import AttrDict

def main(argv):
    #   Don't buffer standard output.
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', -1)

    parser = argparse.ArgumentParser()

    parser.add_argument \
        ('--verbose', dest='verbose', action='count', default=0,
         help='verbosity level')

    #   Parse command-line arguments.
    arg = parser.parse_args()

    raw_data = AttrDict(json.load(sys.stdin));

    if arg.verbose:
        print('raw_data', raw_data, file=sys.stderr)

    payload = base64.b64decode(raw_data.event.awslogs.data)

    if arg.verbose:
        print('payload', payload, file=sys.stderr)

    decompressed = gzip.decompress(payload)

    if arg.verbose:
        print('decompressed', decompressed, file=sys.stderr)

    parsed = json.loads(decompressed)

    if arg.verbose:
        print('parsed', parsed, file=sys.stderr)

    print(json.dumps(parsed, indent=4))

    return 0

#####

if __name__ == '__main__':
    sys.exit(main(sys.argv))
