#!  /usr/bin/env python3

import argparse
import base64
import gzip
import json
import os
import sys

from attrdict import AttrDict


def main(argv):
    parser = argparse.ArgumentParser()

    parser.add_argument \
        ('--verbose', dest='verbose', action='count', default=0,
         help='verbosity level')

    #   Parse command-line arguments.
    arg = parser.parse_args()

    for line in sys.stdin:
        generate_message(line)


def generate_message(line):
    raw_data = AttrDict(json.loads(line));

    payload = base64.b64decode(raw_data.event.awslogs.data)
    decompressed = gzip.decompress(payload)
    parsed = json.loads(decompressed.decode("utf-8"))

    print(json.dumps(parsed, separators=(',',':')))
    sys.stdout.flush()

    return 0


if __name__ == '__main__':
    main(sys.argv)
